# استخدم صورة python الرسمية
FROM python:3.11-slim

# إعداد مجلد العمل داخل الحاوية
WORKDIR /app

# انسخ ملفات المشروع
COPY . /app

# ثبت المتطلبات
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# قم بتحديد متغير البيئة الخاص بتوكن البوت
ENV BOT_TOKEN=8032423352:AAFn2CRF-lrshrnYmFf_TJ7onWER2rD_tDY

# شغّل البوت عند تشغيل الحاوية
CMD ["python", "main.py"]
